#ifndef MES_CONFIG_H
#define MES_CONFIG_H

#define MES_MACHINE_COUNT 9

#define MES_DEFAULT_BASE_URL "http://localhost:8080"
#define MES_DEFAULT_COLLECTOR_CODE "L2-01"
#define MES_DEFAULT_L1_HOST "127.0.0.1"
#define MES_DEFAULT_BASE_PORT 5001
#define MES_DEFAULT_COMMAND_POLL_MS 5000
#define MES_DEFAULT_TELEMETRY_BATCH_MS 10000
#define MES_DEFAULT_AGGREGATION_SECONDS 3600
#define MES_DEFAULT_SENSOR_INTERVAL_MS 1000
#define MES_DEFAULT_INSPECTION_INTERVAL_MS 5000
#define MES_DEFAULT_DEFECT_RATE_PERCENT 5
#define MES_DEFAULT_SPOOL_PATH "runtime/pending.jsonl"

#define MES_TELEMETRY_CAPACITY 4096
#define MES_MAX_EQUIPMENT_CODES 9
#define MES_HTTP_CONNECT_TIMEOUT_SECONDS 3L
#define MES_HTTP_TIMEOUT_SECONDS 10L

#endif
