export const POLLING = Object.freeze({
  COMMUNICATION: 5_000,
  WORK_ORDER: 5_000,
  CURRENT_ALARM: 5_000,
  DEFECT: 5_000,
  TELEMETRY: 10_000,
  HISTORY: 30_000,
  INVENTORY: 30_000,
  PRODUCTION: 60_000,
  STATISTICS: 60_000,
});

const key = (domain, name, params) => [domain, name, params || {}];

export const queryKeys = Object.freeze({
  auth: ["auth"],
  users: (params) => key("users", "list", params),
  pendingUsers: (params) => key("users", "pending", params),
  workers: (params) => key("workers", "list", params),
  products: (params) => key("products", "list", params),
  materials: (params) => key("materials", "list", params),
  processes: () => ["processes"],
  equipments: (params) => key("equipments", "list", params),
  workOrders: (params) => key("work-orders", "list", params),
  workOrder: (id) => ["work-orders", "detail", Number(id)],
  activeWorkOrder: () => ["work-orders", "active"],
  workOrderSummary: () => ["work-orders", "summary"],
  productionResults: (params) => key("production", "results", params),
  productionSummary: (params) => key("production", "summary", params),
  productionGroups: (name, params) => key("production", name, params),
  hourlyProduction: (params) => key("production", "hourly", params),
  alarms: (name, params) => key("alarms", name, params),
  alarm: (id) => ["alarms", "detail", String(id)],
  alarmStatistics: (params) => key("alarms", "statistics", params),
  defects: (params) => key("defects", "list", params),
  defect: (id) => ["defects", "detail", String(id)],
  defectDashboard: () => ["defects", "dashboard"],
  defectStatistics: (params) => key("defects", "statistics", params),
  defectTypes: () => ["defects", "types"],
  l1Devices: () => ["communication", "l1"],
  l2Collectors: () => ["communication", "l2"],
  communicationLogs: (params) => key("communication", "logs", params),
  boms: (params) => key("materials", "boms", params),
  productionLots: (params) => key("materials", "production-lots", params),
  rawMaterialLots: (params) => key("materials", "raw-material-lots", params),
  productInventories: (params) => key("materials", "product-inventories", params),
  inventoryMovements: (params) => key("materials", "movements", params),
});
