import styled, { css } from 'styled-components';

const c = { bg: '#0b1326', lowest: '#060e20', low: '#131b2e', card: '#171f33', high: '#222a3d', border: '#334155', text: '#dae2fd', muted: '#bccbb9', dim: '#869585', green: '#4be277', greenInk: '#003915', amber: '#ffb95f', red: '#ffb4ab' };
const mono = css`font-family: 'JetBrains Mono', Consolas, monospace;`;
const focus = css`&:focus-visible { outline: 2px solid ${c.green}; outline-offset: 2px; }`;

export const Page = styled.main`min-height: 100vh; padding: 32px; background: ${c.bg}; color: ${c.text}; font-family: Inter, sans-serif; *, *::before, *::after { box-sizing: border-box; } button, select, textarea { font: inherit; } @media (max-width: 720px) { padding: 16px; }`;
export const PageHeader = styled.header`display: flex; align-items: flex-start; justify-content: space-between; gap: 20px; margin-bottom: 16px; @media (max-width: 680px) { flex-direction: column; }`;
export const TitleGroup = styled.div`> div { display: flex; align-items: center; gap: 10px; } h1 { margin: 4px 0 8px; font-size: 24px; line-height: 32px; font-weight: 600; } p { margin: 0; color: ${c.muted}; font-size: 14px; }`;
export const Eyebrow = styled.span`color: ${c.green}; font-size: 11px; font-weight: 700; line-height: 16px; letter-spacing: .1em; text-transform: uppercase;`;
export const HeaderActions = styled.div`display: flex; gap: 8px;`;
export const Button = styled.button`${focus} display: inline-flex; align-items: center; justify-content: center; gap: 8px; min-height: 38px; padding: 0 14px; border: 1px solid ${({ $primary }) => ($primary ? c.green : c.border)}; border-radius: 4px; background: ${({ $primary }) => ($primary ? c.green : c.low)}; color: ${({ $primary }) => ($primary ? c.greenInk : c.text)}; font-size: 14px; font-weight: 700; cursor: pointer; &:hover { border-color: ${c.green}; }`;
export const StateSwitch = styled.div`display: inline-flex; padding: 3px; margin-bottom: 16px; border: 1px solid ${c.border}; border-radius: 4px; background: ${c.lowest};`;
export const StateButton = styled.button`${focus} min-width: 92px; min-height: 30px; border: 0; border-radius: 3px; background: ${({ $active }) => ($active ? c.green : 'transparent')}; color: ${({ $active }) => ($active ? c.greenInk : c.muted)}; font-size: 12px; font-weight: 700; cursor: pointer;`;
export const StatusChip = styled.span`${mono} display: inline-flex; padding: 4px 9px; border: 1px solid ${({ $status }) => ($status === '처리 완료' ? `${c.green}66` : `${c.amber}66`)}; border-radius: 999px; background: ${({ $status }) => ($status === '처리 완료' ? `${c.green}18` : `${c.amber}18`)}; color: ${({ $status }) => ($status === '처리 완료' ? c.green : c.amber)}; font-size: 11px; font-weight: 700;`;
export const MetricGrid = styled.section`display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap: 16px; margin-bottom: 16px; @media (max-width: 960px) { grid-template-columns: repeat(2, 1fr); } @media (max-width: 480px) { grid-template-columns: 1fr; }`;
export const MetricCard = styled.article`min-height: 118px; padding: 16px; border: 1px solid ${c.border}; border-radius: 4px; background: ${c.card};`;
export const MetricLabel = styled.div`display: flex; align-items: center; gap: 8px; color: ${c.muted}; font-size: 11px; font-weight: 700; letter-spacing: .08em; text-transform: uppercase; svg { color: ${c.green}; }`;
export const MetricValue = styled.strong`${mono} display: flex; align-items: baseline; gap: 7px; margin-top: 18px; color: ${({ $alarm }) => ($alarm ? c.red : c.text)}; font-size: ${({ $small }) => ($small ? '15px' : '28px')}; line-height: 26px; small { color: ${c.muted}; font-size: 11px; }`;
export const DetailGrid = styled.section`display: grid; grid-template-columns: minmax(0, 8fr) minmax(290px, 4fr); gap: 16px; align-items: start; > div { display: grid; gap: 16px; } @media (max-width: 980px) { grid-template-columns: 1fr; }`;
export const Panel = styled.section`position: ${({ $sticky }) => ($sticky ? 'sticky' : 'static')}; top: 16px; border: 1px solid ${c.border}; border-radius: 4px; background: ${c.card}; @media (max-width: 980px) { position: static; }`;
export const PanelHeader = styled.div`display: flex; align-items: center; justify-content: space-between; gap: 16px; padding: 16px; border-bottom: 1px solid ${c.border}; h2 { margin: 4px 0 0; font-size: 18px; line-height: 24px; }`;
export const PanelLabel = styled.span`color: ${c.green}; font-size: 11px; font-weight: 700; letter-spacing: .1em; text-transform: uppercase;`;
export const InfoGrid = styled.div`display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); @media (max-width: 680px) { grid-template-columns: 1fr 1fr; } @media (max-width: 440px) { grid-template-columns: 1fr; }`;
export const InfoItem = styled.div`display: grid; align-content: start; gap: 5px; min-height: 98px; padding: 16px; border-right: 1px solid ${c.high}; border-bottom: 1px solid ${c.high}; span:first-child { color: ${c.muted}; font-size: 11px; } strong { font-size: 13px; } small { color: ${c.dim}; font-size: 11px; }`;
export const Mono = styled.span`${mono} color: ${c.muted}; font-size: 11px; line-height: 16px;`;
export const Description = styled.p`margin: 0; padding: 20px 16px; color: ${c.muted}; font-size: 14px; line-height: 24px;`;
export const MethodBadge = styled.span`justify-self: start; padding: 4px 8px; border: 1px solid ${c.amber}55; border-radius: 4px; background: ${c.amber}16; color: ${c.amber}; font-size: 11px; font-weight: 700;`;
export const Timeline = styled.div`display: grid; padding: 20px 16px;`;
export const TimelineItem = styled.div`position: relative; display: grid; grid-template-columns: 16px 1fr; gap: 10px; min-height: 76px; &:not(:last-child)::before { content: ''; position: absolute; left: 7px; top: 15px; bottom: -4px; width: 1px; background: ${c.border}; } > div { display: grid; align-content: start; gap: 3px; } strong { font-size: 13px; } div > span:last-child { color: ${c.muted}; font-size: 12px; }`;
export const TimelineDot = styled.span`position: relative; z-index: 1; width: 15px; height: 15px; margin-top: 1px; border: 3px solid ${c.card}; border-radius: 999px; background: ${({ $tone }) => ($tone === 'alarm' ? c.red : $tone === 'warning' ? c.amber : c.green)};`;
export const TreatmentForm = styled.form`display: grid; gap: 16px; padding: 16px;`;
export const FieldGrid = styled.div`display: grid; grid-template-columns: 1fr 1fr; gap: 10px; @media (max-width: 420px) { grid-template-columns: 1fr; }`;
export const Field = styled.div`display: grid; gap: 7px;`;
export const Label = styled.label`font-size: 12px; font-weight: 600;`;
const control = css`width: 100%; min-height: 40px; border: 1px solid ${c.border}; border-radius: 4px; outline: 0; background: ${c.lowest}; color: ${c.text}; font-size: 13px; &:focus { border-color: ${c.green}; }`;
export const Select = styled.select`${control} padding: 0 10px; option { background: ${c.low}; }`;
export const Textarea = styled.textarea`${control} min-height: 100px; padding: 10px; resize: vertical; line-height: 19px;`;
export const FormActions = styled.div`display: flex; justify-content: flex-end; gap: 8px;`;
export const Notice = styled.div`display: flex; align-items: flex-start; gap: 8px; padding: 10px; border: 1px solid ${({ $success }) => ($success ? `${c.green}55` : c.border)}; border-radius: 4px; background: ${c.low}; color: ${({ $success }) => ($success ? c.green : c.muted)}; font-size: 11px; line-height: 16px;`;
export const EmptyState = styled.section`display: grid; justify-items: center; align-content: center; gap: 8px; min-height: 460px; border: 1px solid ${c.border}; border-radius: 4px; background: ${c.card}; color: ${c.muted}; text-align: center; svg { width: 38px; height: 38px; color: ${c.green}; } strong { color: ${c.text}; font-size: 18px; } span { margin-bottom: 8px; font-size: 13px; }`;
