import styled, { css } from 'styled-components';

const c = { bg: '#0b1326', lowest: '#060e20', low: '#131b2e', card: '#171f33', high: '#222a3d', border: '#334155', text: '#dae2fd', muted: '#bccbb9', dim: '#869585', green: '#4be277', greenInk: '#003915', amber: '#ffb95f', red: '#ffb4ab' };
const mono = css`font-family: 'JetBrains Mono', Consolas, monospace;`;
const focus = css`&:focus-visible { outline: 2px solid ${c.green}; outline-offset: 2px; }`;

export const Page = styled.main`min-height: 100vh; padding: 32px; background: ${c.bg}; color: ${c.text}; font-family: Inter, sans-serif; *, *::before, *::after { box-sizing: border-box; } button, select { font: inherit; } @media (max-width: 720px) { padding: 16px; }`;
export const PageHeader = styled.header`display: flex; align-items: flex-start; justify-content: space-between; gap: 20px; margin-bottom: 16px; @media (max-width: 620px) { flex-direction: column; }`;
export const TitleGroup = styled.div`h1 { margin: 4px 0 8px; font-size: 24px; line-height: 32px; font-weight: 600; } p { margin: 0; color: ${c.muted}; font-size: 14px; }`;
export const Eyebrow = styled.span`color: ${c.green}; font-size: 11px; font-weight: 700; line-height: 16px; letter-spacing: .1em; text-transform: uppercase;`;
export const Button = styled.button`${focus} display: inline-flex; align-items: center; gap: 8px; min-height: 38px; padding: 0 14px; border: 1px solid ${c.border}; border-radius: 4px; background: ${c.low}; color: ${c.text}; font-size: 14px; font-weight: 700; cursor: pointer; &:hover { border-color: ${c.green}; }`;
export const ControlRow = styled.section`display: flex; align-items: center; justify-content: space-between; gap: 12px; margin-bottom: 16px; @media (max-width: 520px) { align-items: stretch; flex-direction: column; }`;
export const StateSwitch = styled.div`display: inline-flex; align-self: flex-start; padding: 3px; border: 1px solid ${c.border}; border-radius: 4px; background: ${c.lowest};`;
export const StateButton = styled.button`${focus} min-width: 92px; min-height: 30px; border: 0; border-radius: 3px; background: ${({ $active }) => ($active ? c.green : 'transparent')}; color: ${({ $active }) => ($active ? c.greenInk : c.muted)}; font-size: 12px; font-weight: 700; cursor: pointer;`;
export const SelectField = styled.label`display: flex; align-items: center; gap: 8px; min-width: 180px; height: 40px; padding: 0 10px; border: 1px solid ${c.border}; border-radius: 4px; background: ${c.lowest}; color: ${c.dim}; &:focus-within { border-color: ${c.green}; } select { width: 100%; border: 0; outline: 0; background: transparent; color: ${c.text}; font-size: 13px; } option { background: ${c.low}; }`;
export const MetricGrid = styled.section`display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap: 16px; margin-bottom: 16px; @media (max-width: 960px) { grid-template-columns: repeat(2, 1fr); } @media (max-width: 480px) { grid-template-columns: 1fr; }`;
export const MetricCard = styled.article`min-height: 126px; padding: 16px; border: 1px solid ${c.border}; border-radius: 4px; background: ${c.card}; > span { display: block; margin-top: 5px; color: ${c.dim}; font-size: 11px; }`;
export const MetricLabel = styled.div`display: flex; align-items: center; gap: 8px; color: ${c.muted}; font-size: 11px; font-weight: 700; letter-spacing: .08em; text-transform: uppercase; svg { color: ${c.green}; }`;
export const MetricValue = styled.strong`${mono} display: flex; align-items: baseline; gap: 6px; margin-top: 16px; color: ${({ $warning, $success }) => ($warning ? c.amber : $success ? c.green : c.text)}; font-size: 26px; line-height: 30px; small { color: ${c.muted}; font-size: 11px; }`;
export const StatsGrid = styled.section`display: grid; grid-template-columns: repeat(12, minmax(0, 1fr)); gap: 16px; @media (max-width: 980px) { grid-template-columns: 1fr; }`;
export const Panel = styled.article`grid-column: span ${({ $span }) => $span || '12'}; min-width: 0; border: 1px solid ${c.border}; border-radius: 4px; background: ${c.card}; @media (max-width: 980px) { grid-column: 1; }`;
export const PanelHeader = styled.div`display: flex; align-items: center; justify-content: space-between; gap: 16px; min-height: 70px; padding: 16px; border-bottom: 1px solid ${c.border}; h2 { margin: 4px 0 0; font-size: 18px; line-height: 24px; }`;
export const PanelLabel = styled.span`color: ${c.green}; font-size: 11px; font-weight: 700; letter-spacing: .1em; text-transform: uppercase;`;
export const Mono = styled.span`${mono} color: ${c.muted}; font-size: 11px; line-height: 16px;`;
export const DailyChart = styled.div`display: grid; grid-template-columns: repeat(7, minmax(44px, 1fr)); align-items: end; gap: 12px; min-height: 280px; padding: 24px 18px 18px; overflow-x: auto;`;
export const DailyColumn = styled.div`display: grid; grid-template-rows: 18px 180px 18px; justify-items: center; gap: 8px; > span:last-child { color: ${c.dim}; font-size: 11px; }`;
export const BarTrack = styled.div`display: flex; align-items: flex-end; width: 28px; height: 180px; border-radius: 3px 3px 0 0; background: ${c.lowest};`;
export const BarFill = styled.div`width: 100%; height: ${({ $value }) => `${Math.max($value, 4)}%`}; border-radius: 3px 3px 0 0; background: ${({ $over }) => ($over ? c.amber : c.green)};`;
export const HorizontalList = styled.div`display: grid; gap: 16px; padding: 20px 16px;`;
export const HorizontalItem = styled.div`display: grid; gap: 8px; > div { display: flex; align-items: center; justify-content: space-between; gap: 10px; } strong { font-size: 13px; }`;
export const ProgressTrack = styled.div`height: 8px; overflow: hidden; border-radius: 999px; background: ${c.lowest};`;
export const ProgressFill = styled.div`width: ${({ $value }) => `${$value}%`}; height: 100%; border-radius: inherit; background: ${({ $warning }) => ($warning ? c.amber : c.green)};`;
export const TypeGrid = styled.div`display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 8px; padding: 16px; @media (max-width: 560px) { grid-template-columns: 1fr; }`;
export const TypeCard = styled.div`display: grid; grid-template-columns: 38px minmax(0, 1fr) auto; align-items: center; gap: 10px; min-height: 72px; padding: 10px; border: 1px solid ${c.high}; border-radius: 4px; background: ${c.low}; > div:nth-child(2) { display: grid; gap: 4px; } strong { font-size: 12px; } div span { color: ${c.dim}; font-size: 10px; }`;
export const TypeIcon = styled.span`${mono} display: grid; place-items: center; width: 36px; height: 36px; border: 1px solid ${c.green}44; border-radius: 4px; background: ${c.green}12; color: ${c.green}; font-size: 11px;`;
export const TableWrap = styled.div`overflow-x: auto;`;
export const Table = styled.table`width: 100%; min-width: 680px; border-collapse: collapse; th, td { padding: 12px 16px; border-bottom: 1px solid ${c.high}; text-align: left; } th { color: ${c.muted}; font-size: 11px; letter-spacing: .08em; text-transform: uppercase; } td { font-size: 13px; } tbody tr:nth-child(even) { background: rgba(6, 14, 32, .42); }`;
export const Rank = styled.span`${mono} display: grid; place-items: center; width: 28px; height: 28px; border: 1px solid ${c.border}; border-radius: 4px; background: ${c.low}; color: ${c.green}; font-weight: 700;`;
export const Trend = styled.span`${mono} color: ${({ $up }) => ($up ? c.red : c.green)}; font-size: 11px; font-weight: 700;`;
export const EmptyState = styled.section`display: grid; justify-items: center; align-content: center; gap: 8px; min-height: 460px; border: 1px solid ${c.border}; border-radius: 4px; background: ${c.card}; color: ${c.muted}; text-align: center; svg { width: 38px; height: 38px; color: ${c.green}; } strong { color: ${c.text}; font-size: 18px; } span { font-size: 13px; }`;
