spring.application.name=linecup
mes.l2.stale-after=30s

SPRING_DATASOURCE_URL=jdbc:mysql://127.0.0.1:3306/linecup?useUnicode=true&characterEncoding=utf8&connectionTimeZone=UTC
SPRING_DATASOURCE_USERNAME=linecup_app
SPRING_DATASOURCE_PASSWORD=1234
SPRING_JPA_HIBERNATE_DDL_AUTO=validate
SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_TIME_ZONE=UTC